In [2]:
import pandas as pd

In [10]:
df = pd.read_csv("datasets/sell-in.txt.gz", sep="\t")
df

,periodo,customer_id,product_id,plan_precios_cuidados,cust_request_qty,cust_request_tn,tn
0,201701,10234,20524,0,2,0.05300,0.05300
1,201701,10032,20524,0,1,0.13628,0.13628
2,201701,10217,20524,0,1,0.03028,0.03028
3,201701,10125,20524,0,1,0.02271,0.02271
4,201701,10012,20524,0,11,1.54452,1.54452
...,...,...,...,...,...,...,...
2945813,201912,10105,20853,0,1,0.02230,0.02230
2945814,201912,10092,20853,0,1,0.00669,0.00669
2945815,201912,10006,20853,0,7,0.02898,0.02898
2945816,201912,10018,20853,0,4,0.01561,0.01561
2945817,201912,10020,20853,0,2,0.01561,0.01561

In [28]:
df[df["cust_request_tn"]!=df["tn"]]

,periodo,customer_id,product_id,plan_precios_cuidados,cust_request_qty,cust_request_tn,tn
182,201701,10001,20654,0,7,0.30149,0.26286
812,201701,10003,20313,0,3,13.26780,11.49876
2024,201701,10002,20051,0,11,13.60216,11.96757
2319,201701,10004,20325,0,2,1.93066,1.57248
2840,201701,10002,20424,0,30,1.33235,1.31400
...,...,...,...,...,...,...,...
2944737,201912,10113,20216,0,1,0.58968,0.19656
2944883,201912,10012,20651,0,2,0.17543,0.15479
2945009,201912,10019,20585,0,1,0.33170,0.02211
2945034,201912,10154,20585,0,1,0.11056,0.11057
2945177,201912,10019,20563,0,1,0.33170,0.02211

In [11]:
df.shape

(2945818, 7)

In [12]:
df.describe()

,periodo,customer_id,product_id,plan_precios_cuidados,cust_request_qty,cust_request_tn,tn
count,2.945818e+06,2.945818e+06,2.945818e+06,2.945818e+06,2.945818e+06,2.945818e+06,2.945818e+06
mean,2.018017e+05,1.017148e+04,2.042787e+04,1.155163e-02,2.148753e+00,4.593203e-01,4.497863e-01
std,8.142115e+01,1.421467e+02,3.124612e+02,1.068559e-01,3.571552e+00,3.222836e+00,3.108355e+00
min,2.017010e+05,1.000100e+04,2.000100e+04,0.000000e+00,1.000000e+00,1.000000e-04,1.000000e-04
25%,2.017090e+05,1.005300e+04,2.016100e+04,0.000000e+00,1.000000e+00,1.029000e-02,1.027000e-02
50%,2.018050e+05,1.013300e+04,2.036600e+04,0.000000e+00,1.000000e+00,3.931000e-02,3.931000e-02
75%,2.019030e+05,1.026700e+04,2.065400e+04,0.000000e+00,2.000000e+00,1.572500e-01,1.572500e-01
max,2.019120e+05,1.063700e+04,2.129900e+04,1.000000e+00,9.200000e+01,5.515614e+02,5.478785e+02

In [13]:
len(df["product_id"].unique())

1233

In [18]:
df_series = pd.pivot_table(df,index=["periodo"],columns=["product_id"],values=["tn"],aggfunc="sum",fill_value=0)
df_series.reset_index(inplace=True)
df_series.columns = df_series.columns.map(lambda x: x[1] if x[0] == "tn" else x[0])
df_series.tail(10)

,periodo,20001,20002,20003,20004,20005,20006,20007,20008,20009,...,21290,21291,21292,21293,21294,21295,21296,21297,21298,21299
26,201903,1470.65653,1083.62552,638.04010,619.77084,488.21387,502.43741,576.23305,454.57037,525.47182,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,201904,1647.63848,1287.62346,565.33774,466.70901,624.99880,835.47883,511.54995,403.69191,391.28033,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,201905,1629.78233,1034.98927,590.12515,603.31081,897.26297,527.68846,394.67651,486.36682,578.48564,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,201906,1109.93769,928.36431,662.38654,667.19411,876.39696,458.04180,536.13689,567.42091,610.39590,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,201907,1678.99318,1066.44999,715.20314,521.71519,745.74978,343.11053,573.37257,524.04994,716.07987,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,201908,1261.34529,813.78215,635.59563,482.13372,536.66800,262.73593,307.82899,233.00983,520.41758,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,201909,1660.00561,1090.18771,967.77116,786.17140,879.52808,409.95501,369.74894,330.56343,558.45719,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,201910,1561.50552,1979.53635,1081.36645,1064.69633,996.78275,528.32630,445.34884,452.77197,556.15182,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34,201911,1397.37231,1423.57739,948.29393,723.94206,606.91173,399.61420,357.85913,396.49833,711.89025,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35,201912,1504.68856,1087.30855,892.50129,637.90002,593.24443,417.23228,390.43432,195.36854,495.03574,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [50]:
productos_con_mov  = []
for i in range(1):
    listas += list(df_series.iloc[-i][df_series.iloc[-i]>0].index[1:])
productos_con_mov = list(set(listas))
productos_con_mov.sort()
len(productos_con_mov)

785

In [41]:
df_series.iloc[-1][df_series.iloc[-1]>0]

periodo    201912.00000
20001        1504.68856
20002        1087.30855
20003         892.50129
20004         637.90002
               ...
21265           0.05007
21266           0.05121
21267           0.01569
21271           0.00298
21276           0.00892
Name: 35, Length: 928, dtype: float64